[package]
name = "midevils-soulburn"
version = "0.0.0"
edition = "2021"
readme = "./README.md"
license-file = "../LICENSE"
publish = false

[package.metadata.solana]
program-id = "sLBRn9m2vnahEtgu5RN3Nqm8TxPPRdoYNWT2r6oEv4u"
program-dependencies = [
  "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
]
account-dependencies = []

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = "^0.10"
shank = "^0.4.2"
num-derive = "^0.3"
num-traits = "^0.2"
solana-program = "~2.3"
thiserror = "^1.0"
strum = { version = "0.26.1", features = ["derive"] }
mpl-core = "*"
solana-system-interface = { version = "3.0.0", features = ["bincode"] }
spl-token = { version = "7.0.0", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "7.0.0", features = ["no-entrypoint"] }
solana-program-pack = "3.0.0"
